### ISSUE TITLE
Import von Kriterien geht nicht wenn man nach einem Import Daten gelöscht hat.

### ISSUE THREAD

**Issue by HerrLoesch** [zeiss-digital-innovation/ToolComparision#14]
Wiederherstellungsschritte:
1. 3 Kriterien anlegen.
2. Kriterien exportieren.
3. Seite neu aufrufen
4. Kriterien importieren
5. 2 Kriterien löschen
6. Erneut importieren
X Fehler X die gelöschten Kriterien sind nicht sichtbar.

**Comment by ZDI-StephanJoneleit** [comment]
Anmerkung: Das Problem war das input event, welches nicht getriggert wird wenn 2x hintereinander diesselbe Datei ausgewählt wird.
Jetzt wird wieder das change event verwendet, die value aber nach dem laden resetted, womit alle Dateien als neue (change) behandelt werden.
